# MUST REFLECT pinout.h IN RASPBERRYLATTE-PICO!!!!!

SCALE_CLOCK_PIN            2
SCALE_DATA_PIN             3
PHASE_CONTROL_0CROSS_PIN   4
SOLENOID_PIN               5
LMT01_DATA_PIN             6
DIAL_A_PIN                 7
DIAL_B_PIN                 8
PUMP_SWITCH_PIN            9
PHASE_CONTROL_OUT_PIN      10
HEATER_PWM_PIN             11
PRESSURE_SENSOR_PIN        28
LED0_PIN 12
LED1_PIN 13
LED2_PIN 14